export const initialFormData = {
    Doc_No: "",
    supplyType: "",
    subType: "",
    docType: "INV",
    doc_date: new Date().toISOString().split("T")[0],
    Company_Name_E: "",
    Address_E: "",
    GST: "",
    City_E: "",
    State_E: "",
    PIN: "",
    EmailId: "",
    GSTRate: "",
    LESS_FRT_RATE: 0.0,
    LORRYNO: "",
    Buyer_Name: "",
    Buyer_Address: "",
    BuyerGst_No: "",
    Buyer_City: "",
    Buyer_State_Code: 0,
    Buyer_State_name: "",
    Buyer_Phno: "",
    Buyer_Email_Id: "",
    Buyer_State_name: "",
    Buyer_Pincode: "",
    System_Name_E: "",
    Mode_of_Payment: "",
    ShipToGst_No: "",
    ShipTo_Address: "",
    ShipTo_City: "",
    ShipTo_GSTStateCode: 0,
    ShipTo_Name: "",
    ShipTo_Pincode: 0,
   // itemDescription: "",
    HSN: "",
    NETQNTL: 0.0,
    unit: "QTL",
    taxableValue: 0.0,
    CGSTRate: 0.0,
    SGSTRate: 0.0,
    IGSTRate: 0.0,
    CGSTAmount: 0.0,
    SGSTAmount: 0.0,
    IGSTAmount: 0.0,
    DispatchCity_City: " ",
    DispatchGst_No: "",
    Dispatch_Address: "",
    Dispatch_GSTStateCode: 0,
    GSTStateCode: 0,
    Dispatch_Name: "",
    Dispatch_Pincode: 0,
    Distance: 0.0,
    PHONE: "",
    Account_Details: "",
    Branch: "",
    IsService: "N",
    TaxableAmount: 0.00,
    otherAmount:0.00,
    billAmount:0.00,
    transporterName: "",
    transporterID: "",
    approximateDistance: 0.00,
    tranceMode: "1",
    vehicleType: "R",
    rate: "",
    reverseCharge: "N",
    IGSTOnIntra: "N",
    cessValue: 0.0,
    discount: 0.0,
    payeeName:"",
    cessAmount:0.00,
    stateCessValue:0.00,
    billFromAdd:"",
    BuyerAdd1:"",
    dispatchAdd:"",
    shipToAdd:""
  };